theme: jekyll-theme-minimal

title: Kubeflow Kale
description: A simple tool for direct and autoamtic deployments of Jupypter Notebooks to Kubeflow Pipelines

logo: ./logo.png
show_downloads: true

github:
  zip_url: https://github.com/kubeflow-kale/kale/zipball/master
  tar_url: https://github.com/kubeflow-kale/kale/tarball/master
  repository_url: https://github.com/kubeflow-kale/kale
